name: archiarena
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1
environment:
  sdk: ^3.9.2
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.6.6
  image_picker: ^1.0.7
  record: ^6.0.0
  audioplayers: ^6.0.0
  path_provider: ^2.1.0
  connectivity_plus: ^6.0.0
  internet_connection_checker: ^1.0.0+1
  shared_preferences: ^2.3.0
  dio: ^5.4.0
  shimmer: ^3.0.0
  firebase_core: ^3.8.1
  firebase_messaging: ^15.1.5
  flutter_local_notifications: ^18.0.1
  open_file: ^3.3.2
  file_picker: ^8.0.0
  cached_network_image: ^3.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/
