// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhiK9tg5RI_1PGkil0Tbps9wSA2wuJ1kI',
    appId: '1:475061185169:web:cc67c32d9fa05a20cd2d30',
    messagingSenderId: '475061185169',
    projectId: 'archiarena-2548d',
    authDomain: 'archiarena-2548d.firebaseapp.com',
    storageBucket: 'archiarena-2548d.firebasestorage.app',
    measurementId: 'G-TEZM9WX5QL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-7HSVYr2xzHaWVCEgCsf6oziavXWEHys',
    appId: '1:475061185169:android:9aed06bd1924c817cd2d30',
    messagingSenderId: '475061185169',
    projectId: 'archiarena-2548d',
    storageBucket: 'archiarena-2548d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvF0vQtjGqvY9iZGwh-eIJiEEs3BD23fw',
    appId: '1:475061185169:ios:af16f8ff51e69d94cd2d30',
    messagingSenderId: '475061185169',
    projectId: 'archiarena-2548d',
    storageBucket: 'archiarena-2548d.firebasestorage.app',
    iosBundleId: 'com.ahmadghneem.archiarenafordesginers',
  );
}
