// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNo5I2htryLHT3PK3xH4B53pF5S5uDZQU',
    appId: '1:768499589240:web:ab4145be82d484d9dc0d8d',
    messagingSenderId: '768499589240',
    projectId: 'archarena-78166',
    authDomain: 'archarena-78166.firebaseapp.com',
    storageBucket: 'archarena-78166.firebasestorage.app',
    measurementId: 'G-W0TMCGG1RW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDt7WkIEtA9GFjqOAaU1Em9vMc8SxRCvxo',
    appId: '1:768499589240:android:f3602ef5addac6b8dc0d8d',
    messagingSenderId: '768499589240',
    projectId: 'archarena-78166',
    storageBucket: 'archarena-78166.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqkifm5MnIi9YGOSc6S0nhywoNnB1Lhx8',
    appId: '1:768499589240:ios:50932c48a486f9ecdc0d8d',
    messagingSenderId: '768499589240',
    projectId: 'archarena-78166',
    storageBucket: 'archarena-78166.firebasestorage.app',
    iosBundleId: 'com.ahmadghneem.archarena',
  );
}
