import 'package:get/get.dart';

class MyLocal extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
    'en': {
      "login_easily": "Login easily and securely",
      "enter_mobile_otp": "Enter your mobile number and the verification code sent to your mobile",
      "mobile_number": "Mobile Number",
      "login": "Login",
      "register": "Register",
      "dont_have_account": "Don't have an account?",
      "download_nafath": "You can download Nafath app via",
      "nafath_convenience": "For your convenience, you can register in the app using the national 'Nafath' service.",
      "id_number": "ID Number",
      "choose_nafath_number": "Choose this number in Nafath app to login",
      "click_after_confirm": "Click here after confirming the number in Nafath",
      "logged_in_success": "Logged in successfully",
      "agree_to_all": "I agree to all ",
      "terms_privacy": "Terms of Service and Privacy Policy",
      "have_account": "Have an account? ",
      "done": "Done",
      "error": "Error",
      "error_picking_image": "Error picking image",
      "change_profile_pic": "Change Profile Picture",
      "take_photo": "Take Photo",
      "choose_gallery": "Choose from Gallery",
      "delete_photo": "Delete Photo",
      "language": "Language",
      "arabic": "Arabic",
      "english": "English",
      "save_changes": "Save Changes",
      "select_language": "Select Language",
      "otp_verified_success": "OTP verified successfully",
      "incorrect_code": "Incorrect code entered",
      "code_will_be_resent": "Code will be resent to your number",
      "resend_code_sms": "Resend Code (SMS)",
      "resend_code_whatsapp": "Resend Code via WhatsApp",
      "send_code_whatsapp": "Send Code via WhatsApp",
      "otp_verification": "OTP Verification",
      "enter_otp_msg": "Please enter the 4-digit code sent via SMS to your mobile number",
      "confirm": "Confirm",
      "remember_me": "Remember Me",
      
      // Home & Order
      "order_status_num": "Order Status #",
      "show": "Show",
      "hide": "Hide",
      "my_orders": "My Orders",
      "orders_pending": "Pending Orders",
      "orders_processing": "Processing Orders",
      "orders_completed": "Completed Orders",
      "create_new_order": "Create New Order",
      "order_completed_80": "80% of the way completed",
      "in_progress": "In Progress",
      "driver_arrival_time": "Driver arrives in 15 mins",
      "view_details": "View Details",
      "display_all": "View All",
      "orders": "Orders",
      "promo_20_off": "20% Discount on Delivery",
      "promo_3_days": "Offer valid for 3 days only",
      "promo_15_off": "15% off Express Shipping",
      "promo_2_days": "Offer for 2 days only",
      "promo_10_off": "10% off for New Customers",
      "promo_hurry": "Hurry before time runs out",
      "view_more": "View More",
      "order_list": "Order List",
      "order_number": "Order #",
      "view": "View",
      "back_to_order": "Back to Order",
      "orders_history": "Orders History",
      "create_transport_order": "Create Transport Order",
      "shipment_order_data": "Shipment & Order Data",
      "order_type": "Order Type",
      "port": "Port",
      "freight_type": "Freight Type",
      "freight_weight": "Freight Weight",
      "goods_value": "Goods Value",
      "empty_return": "Empty Return Available",
      "next": "Next",
      "cancel": "Cancel",
      "receiver_order_data": "Receiver & Order Data",
      "delivery_address": "Delivery Address",
      "distance_km": "Distance (km)",
      "receiver_name": "Receiver Name",
      "name": "Name",
      "receiver_mobile": "Receiver Mobile",
      "number": "Number",
      "alert": "Alert",
      "enter_receiver_mobile": "Please enter receiver mobile",
      "back": "Back",
      "attachments_notes": "Attachments & Notes",
      "attachments": "Attachments",
      "attach_pdf": "Attach PDF",
      "max_5mb": "Max 5MB",
      "upload_pdf": "Upload PDF",
      "uploading": "Uploading...",
      "completed": "Completed",
      "additional_notes": "Additional Notes",
      "write_notes_here": "Write your notes here",
      "calculate_price": "Calculate Price",
      "details_price": "Details & Price",
      "customs_declaration": "Customs Declaration No",
      "order_date": "Order Date",
      "is_return": "Is there return",
      "start_point": "Start Point",
      "end_point": "End Point",
      "final_price": "Final Transport Price",
      "confirm_create_order": "Confirm Price & Create Order",
      "accept_terms_privacy_required": "You must accept Terms of Service and Privacy Policy",
      "price_approved": "Price approved successfully.",
      "searching_driver": "Searching for best carrier...",
      "driver_found": "Driver found for your order",
      "driver_on_way": "Driver is on the way, you can track updates on the map",
      "map": "Map",
      "edit_order": "Edit Order",
      "calculating_best_price": "Calculating best price for you",
      "price_calc_time": "Calculating price takes less than a minute.",
      "confirm_cancellation": "Confirm Cancellation",
      "cancel_confirm_msg": "Are you sure you want to cancel the shipment request? The shipment will not be sent.",
      "yes_cancel": "Yes, Cancel Order",
      "cancel_success": "Order cancelled successfully, you can retry anytime",
      "no_return_price": "No, return to price page",
      "fill_all_data": "Please fill all required data",

      // Dropdowns
      "choose": "Choose...",
      "shipment_from_port": "Shipment from Port",
      "shipment_from_warehouse": "Shipment from Warehouse",
      "jeddah_port": "Jeddah Port",
      "dammam_port": "Dammam Port",
      "general_goods": "General Goods",
      "liquid_materials": "Liquid Materials",
      "10_ton": "10 Ton",
      "20_ton": "20 Ton",
      "50_ton": "50 Ton",
      "100_sar": "100 SAR",
      "500_sar": "500 SAR",
      "1000_sar": "1000 SAR",
      "5_km": "5 Km",
      "10_km": "10 Km",
      "20_km": "20 Km",
      "yes": "Yes",
      "no": "No",
      "please_enter_id": "Please enter ID number",
      "agree_terms_required": "You must agree to Terms of Service",
      "connecting_nafath": "Connecting to Nafath service..."
    },
    'ar': {
      "login_easily": "تسجيل الدخول بسهولة وأمان",
      "enter_mobile_otp": "ادخل رقم الجوال الخاص بك وادخل كود التحقق المرسل إلى جوالك",
      "mobile_number": "رقم الجوال",
      "login": "تسجيل الدخول",
      "register": "التسجيل",
      "dont_have_account": "أليس لديك حساب ؟",
      "download_nafath": "يمكنك تحميل تطبيق نفاذ بواسطة",
      "nafath_convenience": "لراحتك، يمكنك التسجيل في التطبيق باستخدام خدمة \"نفاذ\" الوطنية.",
      "id_number": "رقم الهوية",
      "choose_nafath_number": "اختر هذا الرقم من تطبيق نفاذ للدخول",
      "click_after_confirm": "اضغط هنا بعد تأكيد الرقم في نفاذ",
      "logged_in_success": "تم تسجيل الدخول",
      "agree_to_all": "أوافق على جميع ",
      "terms_privacy": "شروط الخدمة وسياسة الخصوصية",
      "have_account": "لديك حساب؟ ",
      "done": "تم",
      "error": "خطأ",
      "error_picking_image": "حدث خطأ أثناء اختيار الصورة",
      "change_profile_pic": "تغيير الصورة الشخصية",
      "take_photo": "التقاط صورة",
      "choose_gallery": "اختر من المعرض",
      "delete_photo": "حذف الصورة",
      "language": "اللغة",
      "arabic": "اللغة العربية",
      "english": "English",
      "save_changes": "حفظ التغييرات",
      "select_language": "اختيار اللغة",
      "otp_verified_success": "تم التحقق من كود OTP بنجاح",
      "incorrect_code": "لم يتم ادخال الكود بشكل صحيح",
      "code_will_be_resent": "سيتم إعادة إرسال الكود الى رقمك",
      "resend_code_sms": "إعادة إرسال الكود (SMS)",
      "resend_code_whatsapp": "إعادة إرسال الكود عن طريق واتساب",
      "send_code_whatsapp": "ارسال الكود عن طريق واتساب",
      "otp_verification": "OTP التحقق من كود",
      "enter_otp_msg": "الرجاء إدخال رمز التحقق المكوّن من 4 أرقام الذي تم إرساله كرسالة قصيرة (SMS) إلى رقمك الجوال",
      "confirm": "تأكيد",
      "remember_me": "تذكرني",

      // Home & Order
      "order_status_num": "حالة الطلب رقم ",
      "show": "عرض",
      "hide": "إخفاء",
      "my_orders": "طلباتي",
      "orders_pending": "الطلبات قيد الانتظار",
      "orders_processing": "الطلبات قيد التنفيذ",
      "orders_completed": "الطلبات المكتملة (تم التسليم)",
      "create_new_order": "إنشاء طلب جديد",
      "order_completed_80": "لقد تم اكمال 80% من الطريق",
      "in_progress": "قيد التنفيذ",
      "driver_arrival_time": "سيصل السائق خلال ربع ساعة",
      "view_details": "عرض التفاصيل",
      "display_all": "عرض الكل",
      "orders": "طلبات",
      "promo_20_off": "٪20 حسم للتوصيل",
      "promo_3_days": "هذا العرض متوفر لـ 3 أيام فقط",
      "promo_15_off": "خصم 15% على الشحن السريع",
      "promo_2_days": "العرض لمدة يومين فقط",
      "promo_10_off": "خصم 10% للعملاء الجدد",
      "promo_hurry": "سارع قبل انتهاء الوقت",
      "view_more": "عرض المزيد",
      "order_list": "قائمة الطلبات",
      "order_number": "رقم الطلب:",
      "view": "عرض",
      "back_to_order": "رجوع لصفحة الطلب",
      "orders_history": "سجل الطلبات",
      "create_transport_order": "إنشاء طلب نقل",
      "shipment_order_data": "بيانات الشحنة والطلب",
      "order_type": "نوع الطلب",
      "port": "الميناء",
      "freight_type": "نوع الحمولة",
      "freight_weight": "وزن الحمولة",
      "goods_value": "قيمة البضاعة",
      "empty_return": "يوجد إرجاع فارغ",
      "next": "التالي",
      "cancel": "إلغاء",
      "receiver_order_data": "بيانات المستلم والطلب",
      "delivery_address": "عنوان التسليم",
      "distance_km": "المسافة (كم)",
      "receiver_name": "اسم المستلم",
      "name": "الاسم",
      "receiver_mobile": "جوال المستلم",
      "number": "الرقم",
      "alert": "تنبيه",
      "enter_receiver_mobile": "يرجى إدخال جوال المستلم",
      "back": "رجوع",
      "attachments_notes": "مرفقات وملاحظات",
      "attachments": "المرفقات",
      "attach_pdf": "أرفق ملف PDF",
      "max_5mb": "بحد أقصى 5MB",
      "upload_pdf": "تحميل ملف PDF",
      "uploading": "جاري التحميل...",
      "completed": "مكتمل",
      "additional_notes": "ملاحظات إضافية",
      "write_notes_here": "اكتب ملاحظاتك هنا",
      "calculate_price": "حساب السعر",
      "details_price": "التفاصيل والسعر",
      "customs_declaration": "رقم البيان الجمركي",
      "order_date": "تاريخ الطلب",
      "is_return": "هل يوجد إرجاع",
      "start_point": "البداية",
      "end_point": "الوصول",
      "final_price": "السعر النهائي لخدمة النقل",
      "confirm_create_order": "الموافقة على السعر وإنشاء الطلب",
      "accept_terms_privacy_required": "يجب الموافقة على شروط الخدمة وسياسة الخصوصية",
      "price_approved": " تم تأكيد موافقتك على السعر.",
      "searching_driver": "جار البحث عن أفضل ناقل لخدمتك ..",
      "driver_found": " تم إيجاد سائق لنقل طلبك",
      "driver_on_way": "السائق في الطريق اليك , يمكنك متابعة التحديثات في الخريطة",
      "map": "الخريطة",
      "edit_order": "تعديل الطلب",
      "calculating_best_price": "جاري حساب أفضل سعر لك",
      "price_calc_time": "يستغرق حساب السعر المناسب أقل من دقيقة.",
      "confirm_cancellation": "تأكيد الإلغاء",
      "cancel_confirm_msg": "هل أنت متأكد بأنك تريد إلغاء طلب توصيل الشحنة؟\لن يتم إرسال الشحنة من موقع الانطلاق إلى الوجهة المحددة",
      "yes_cancel": "نعم، إلغاء الطلب",
      "cancel_success": " تم إلغاء الطلب بنجاح و يمكنك\ إعادة المحاولة في أي وقت",
      "no_return_price": "لا، الرجوع لصفحة السعر",
      "fill_all_data": "يرجى تعبئة جميع البيانات المطلوبة",

      // Dropdowns
      "choose": "اختر...",
      "shipment_from_port": "شحنة من ميناء",
      "shipment_from_warehouse": "شحنة من مستودع",
      "jeddah_port": "ميناء جدة",
      "dammam_port": "ميناء الدمام",
      "general_goods": "بضائع عامة",
      "liquid_materials": "مواد سائلة",
      "10_ton": "10 طن",
      "20_ton": "20 طن",
      "50_ton": "50 طن",
      "100_sar": "100 ريال",
      "500_sar": "500 ريال",
      "1000_sar": "1000 ريال",
      "5_km": "5 كم",
      "10_km": "10 كم",
      "20_km": "20 كم",
      "yes": "نعم",
      "no": "لا",
      "please_enter_id": "يرجى إدخال رقم الهوية",
      "agree_terms_required": "يجب الموافقة على شروط الخدمة",
      "connecting_nafath": "جاري الاتصال بخدمة نفاذ..."
    },
  };
}
